name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: Set up Node.js if you are using a build tool like npm (only if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Optional: Install dependencies (if you're building the project)
      - name: Install dependencies
        run: npm install

      # Optional: Build your project (e.g., if using Webpack, React, etc.)
      - name: Build the project
        run: npm run build  # Or another build command for your project

      # Upload the folder containing your static content (public folder, or wherever your built files are)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # Upload the contents of the public folder or wherever your build files are

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
